name: Deploy to AWS EC2

on:
  push:
    branches:
      - master  # Gatilho para a branch principal

env:
  NODE_VERSION: '20'
  APP_DIRECTORY: '~/Minden/api-minden'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      # 1. Faz o checkout do repositório
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      # 2. Configura o Node.js na versão especificada
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: 'api-minden/package-lock.json'

      # 3. Instala dependências no GitHub Actions para garantir consistência
      - name: Install Dependencies
        working-directory: api-minden
        run: npm ci

      # 4. Compila o TypeScript no ambiente de CI para validação
      - name: Compile TypeScript
        working-directory: api-minden
        run: npx tsc

      # 5. Conecta à instância EC2 e realiza o deploy
      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            set -e  # Encerra o script se algum comando falhar
            
            echo "Navigating to application directory..."
            cd ${{ env.APP_DIRECTORY }}
            
            echo "Creating the .env file..."
            cat <<EOF > .env
            DB_NAME="minden"
            DB_HOST="localhost"
            DB_USER="${{ secrets.DB_USER }}"
            DB_PASSWORD=" ${{ secrets.DB_PASSWORD }}"
            PORT=8000
            EOF
            
            echo "Stopping the current application..."
            pm2 stop app || true  # Para o processo caso já esteja em execução
            
            echo "Updating code from GitHub..."
            git fetch origin
            git reset --hard origin/master
            
            echo "Installing dependencies..."
            npm ci  # Instala as dependências no ambiente de produção
            
            echo "Compiling TypeScript..."
            npx tsc
            
            echo "Starting the application with PM2..."
            pm2 start npm --name "app" -- start || pm2 restart app
